### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by didim99** [infeeeee/py-nocodb#2]
I want to see this package available in PyPI, @infeeeee are you consider to publish your work? If not, can I publish it myself (from my own fork)?

**Comment by infeeeee** [comment]
Yep, I'm planning to do it sometime. It seems without any marketing you found this repo so I will take a look how I can do that.

Until that you can already use this repo as a dependency e.g. in `pyproject.toml` add this:

```toml
dependencies = [
    "py-nocodb@git+https://github.com/infeeeee/py-nocodb",
]
```

Than import should work:


```python
from nocodb import NocoDB
```

**Comment by didim99** [comment]
> you can already use this repo as a dependency e.g. in pyproject.toml add this

Of course, but publishing in PyPI make it available for significantly more developers, today we have only one library supporting NocoDB API v2 in PyPI ([pynocodb](https://pypi.org/project/pynocodb/)) and it does not have a source code published on any known place like Github (it seems to be developed by some Chinese user).

I will by stay tuned for PyPI release, thank you!

**Comment by infeeeee** [comment]
I already have another package on pypi, I can just copypaste the workflow from there. Lets keep this open until I published this

**Comment by infeeeee** [comment]
Done! Pypi didn't let me use the name of the repo as it's too similar to others, I came up with this.

```shell
pip install nocodb-api
```

Should I change the name of the gh repo as well? I don't really like that this project has 3 names. What do you think?

**Comment by didim99** [comment]
> What do you think?

Of course, if you prefer unified naming (me too), you can rename repo.

**Comment by infeeeee** [comment]
Repo name updated.
